services:
   db:
    image: mysql:8.0
    container_name: logicea-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'cards'